### ISSUE TITLE
Downloading Unreadable Content 

### ISSUE THREAD

**Issue by mxu2000** [uchicago-capp-30320/DataForGood-chicago#10]
Hi James and Michael,

As discussed in today's meeting, I tried to create a "Download Memo" button in our dataandvisualize.html template, which will download a .docx file containing the generated memo's content. 

However, when I tried to test it out, I get a pop up which says that the content is "unreadable." I'm currently inputting the generated contents using the python-docx library. The code associated with this is in the savememo() function (lines 230-257) in the utils.py file (DataForGood-chicago/dataforgood/main/utils.py in the front-back-merge-testing branch) and lines 266-287 in views.py (DataForGood-chicago/dataforgood/main/views.py in the same branch).

The code associated with creating the button which the user can click is in dataandvisualize.html (DataForGood-chicago/dataforgood/main/templates/dataandvisualize.html  in the same branch) in lines 792-796.

**Comment by jamesturk** [comment]
I've taken a look at this, it seems like the docx generation is working locally the issue is likely in how you are having the download read from the disk.

Typically what you want to do is have a Django view that returns the actual docx data, this stackoverflow shows what that could look like:

https://stackoverflow.com/questions/19400089/downloadable-docx-file-in-django

You want to have your code call a view that generates the DOCX, so you would add a URL like "/download-docx/" that would contain the code above.
