### ISSUE TITLE
Folium multiple legends issue

### ISSUE THREAD

**Issue by mxu2000** [uchicago-capp-30320/DataForGood-chicago#9]
Hi James and Michael,

As discussed in today's meeting, I'm having trouble with displaying the heat maps for different years of the same geographic areas. Currently, if a user selects 3 years, 3 heat maps are generated and three legends appear on the first map (instead of one unique legend per map). My methodology for creating the heat maps involves looping through each year's data, making a new map, and saving the HTML file and its path (which is then called in the dataandvisualize.html template). 

The code associated with this issue is lines 153-264 in the views.py file (DataForGood-chicago/dataforgood/main/views.py)  in the front-back-merge testing branch. The code associated with calling the map's HTML path in dataandvisualize.html (DataForGood-chicago/dataforgood/main/templates/dataandvisualize.html) in the front-back-merge testing branch is lines 477-486.

**Comment by jamesturk** [comment]
I don't have a specific fix for you here, but a few thoughts on what is happening now:

1) The function is very long and tough to follow, I'd recommend more comments and/or breaking into smaller functions. I spent a bit of time with it and think I understand the relevant portion now, but less than confident I didn't miss something.
2) I think that one thing that would help would be factoring out the map generation code so you can run/test it independently. Even if it's a manual test, it'd be good to be able to generate a single map in a function instead of having all of the code nested in a for loop.

These would likely help surface the issue, which is likely due to some state being shared between subsequent calls to the mapping functions.

Finally this isn't the cause of the issue, but if you are refactoring a bit to solve the problem it may be worth considering this: I'm not sure if implementing this will be practical, but there are some bigger picture architectural issues with writing HTML to disk and serving it out that way.  Writing to disk is slow & unreliable, and this approach will eventually fill a machine's disk space causing failures.  (Also hosts like Heroku may not allow deployment of things that write to disk in this way.)

Instead wherever you want specific HTML, in a web context you typically write a new view, with a new URL, something like /heatmap/?city=chicago&year=2023 that would return the HTML as a response.  Then you can use those URLs instead of HTML from disk.
